database:
  enabled: false
  url: 'jdbc:mysql://localhost:3306'
  database: 'test'
  username: 'root'
  password: 'test'

chat:
  replacements:
    ':)': 'ğŸ˜‚'
    '<3': 'â¤'
    '(r)': 'Â®'
    '(c)': 'Â©'
    ';)': 'ãƒ„'
    '>>': 'Â»'
    '<<': 'Â«'
    '...': 'â€¦'
    '>_<': 'â€º_â€¹'