database:
  enabled: false
  url: 'jdbc:mysql://localhost:3306'
  database: 'test'
  username: 'root'
  password: 'test'

chat:
  replacements:
    ':pandasad': '父'
    ':eyes': '火'
    'eyessus': '升'
    ':f': '互'
    ':kappa': '水'
    ':kekw': '勿'
    ':know': '匂'
    ':monkas': '呂'
    ':pandahug': '夫'
    ':pandalove': '太'
    ':pandalurk': '収'
    ':happy': '双'
    ':pepe5head': '及'
    ':pepeg': '午'
    ':pepeheart': '手'
    ':pepeok': '己'
    ':pepepolice': '巾'
    ':peperetarded': '川'
    ':pepecool': '今'
    ':pepega': '斗'
    ':pepehands': '旦'
    ':pepesadge': '曰'
    ':sheesh': '月'
    ':thonk': '木'


