database:
  enabled: false
  url: 'jdbc:mysql://localhost:3306'
  database: 'test'
  username: 'root'
  password: 'test'

chat:
  replacements:
    ':)': 'ğŸ˜‚'
    ':panda': 'çˆ¶'
    ':eyes': 'ç«'
    'eyessus': 'å‡'
    ':f': 'äº’'
    ':kappa': 'æ°´'
    ':kekw': 'å‹¿'
    ':know': 'åŒ‚'
    ':monkas': 'å‘‚'
    ':pandahug': 'å¤«'
    ':pandalove': 'å¤ª'
    ':pandalurk': 'å'
    ':happy': 'åŒ'
    ':pepe5head': 'åŠ'
    ':pepeg': 'åˆ'
    ':pepeheart': 'æ‰‹'
    ':pepeok': 'å·±'
    ':pepepolice': 'å·¾'
    ':peperetarded': 'å·'
    ':pepecool': 'ä»Š'
    ':pepega': 'æ–—'
    ':pepehands': 'æ—¦'
    ':pepesadge': 'æ›°'
    ':sheesh': 'æœˆ'
    ':thonk': 'æœ¨'


