database:
  url: 'jdbc:mysql://localhost:3306'
  database: 'test'
  username: 'root'
  password: 'test'

chat:
  replacements:
    ':)': '☺'
    '<3': '❤'
    '(r)': '®'
    '(c)': '©'
    ';)': 'ツ'
    '>>': '»'
    '<<': '«'
    '...': '…'
    '>_<': '›_‹'